### ISSUE TITLE
Duplicate p end tag in excerpts

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#128]
A recent commit has introduced this HTML issue:

https://rocketvalidator.com/s/6f75c943-9b77-4f5d-a87d-1dfc6094c551/i/113585449

Clicking on the details for a page affected, you can see the lines where this appear on the code, for example:

<img width="826" alt="Captura de pantalla 2021-08-28 a las 10 18 02" src="https://user-images.githubusercontent.com/2629/131211440-dd3c7e14-e016-4a7d-9364-14b0c8b9469c.png">

@kinson I think this was introduced in your last commit but I can't see where is the `</p>` being duplicated, any idea?

**Comment by kinson** [comment]
Good catch by RV! While we obviously don't want unnecessary tags, I am curious why this was reported error:

`An end tag </p> has been found that cannot be matched for an opening tag <p>. Most of the times this is due to closing the same tag twice, for example:`

Looking at the report (and your example), it appears that there is not a missing `<p>` tag, just an extra set of `<p>` tags. Am I misunderstanding the report or the issue?

**Comment by jaimeiniesta** [comment]
Well it looks like this has been fixed in #129 - I've re-checked the affected pages and the issue is gone!

@kinson I believe the issue was correct, from my screenshot you can see an extra closing `</p>` tag, like `<p class="excerpt">some text</p></p>`, right?

**Comment by jaimeiniesta** [comment]
Ah @kinson now that I see it better, the problem was a nested `<p>` inside another `<p>`. If you go to the [w3c validator](https://validator.w3.org/nu/#textarea) you can check this is incorrect:

```html
<!DOCTYPE html>
<html lang="">
<head>
<title>Test</title>
</head>
<body>
<p><p></p></p>
</body>
</html>
```

**Comment by kinson** [comment]
To me it looks like in the example you posted there is an opening tag on line 519 & 520 and then a closing tag on lines 521 & 523 - so 2 opening tags and 2 corresponding closing tags.
