### ISSUE TITLE
Add "coming soon" badge to lessons in the menu

### ISSUE THREAD

**Issue by doomspork** [elixirschool/school_house#135]
We have support for "coming soon" lessons in the menu but we don't have any call out other than a disabled cursor. @kinson suggested using a badge 👍

**Comment by rsmidt** [comment]
I'd love to take this issue. Is it still free?

**Comment by rsmidt** [comment]
I did a quick sketch. 
![image](https://user-images.githubusercontent.com/15527639/136074318-9c71ebd9-d800-4fc6-af8a-8688fd457b7f.png)

It looks good to me but for longer entries the text breaks. Same for mobile. Is that ok? Otherwise, we could just put "Soon" in the badge.

**Comment by kinson** [comment]
@rsmidt wow this is great! I think that looks good too, the line breaks are not a big deal in my opinion.

One suggestion I have looking at the `Querying: Advanced` example: I think it may look better to put the "coming soon" tag inline with the text instead of aligning it vertically with the text container. In this instance it would look something like:

```
Querying:
Advanced [Coming Soon]
```

or on smaller view ports:

```
Querying:
Advanced
[Coming Soon]
```

Let me know what you think though 😄 - either way thanks for tackling this!

**Comment by doomspork** [comment]
Thank you @rsmidt and @kinson for getting this worked out 🙏
